const INCORRECT_DATA_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const AUTHORIZED_BUT_FORBIDDEN_ERROR_CODE = 403;
const DATA_NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  INCORRECT_DATA_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  AUTHORIZED_BUT_FORBIDDEN_ERROR_CODE,
  DATA_NOT_FOUND_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  MONGO_DUPLICATE_ERROR_CODE,
};
